Server implementation & Create Response work fine.
BasicAlgorithm/Protocol-HSM pull request #34
Opened 2021-05-03 09:50 UTC by BasicAlgorithm

2021-05-03 13:46 UTC, rodp63 commented
Todo ok, ya funciona el login, broadcast y lista. Las funciones `exit` y `message` dan algunos errores, pero deben ser tratados en otro issue.

2021-05-03 14:50 UTC, mgonnav requested changes

2021-05-03 14:50 UTC, mgonnav commented on src/HSMP/HSMPRequest.cpp
> +  if (this->msg.length() <= 99) {
Por qué usas `this->msg.length()` cuando ya tenemos el tamaño directamente en `this->tam_msg`?

2021-05-03 14:50 UTC, mgonnav commented on src/HSMP/HSMPRequest.cpp
> +                                              std::list<std::string> &logs
`logs` no debería pasarse a ProcessRequest. En todo caso, que logs sea `static`.

2021-05-03 14:50 UTC, mgonnav commented on src/server.cpp
> +  User *current_user;
Please use smart pointers

2021-05-03 14:50 UTC, mgonnav commented on src/server.cpp
> +const std::string kMessageErrorUserDontExist ("[HSMP] user_no_exist");
Hay forma de poner los tipos de error en un `enum` y según eso devolver el mensaje de error?

2021-05-03 14:50 UTC, mgonnav commented on src/server.cpp
>  const std::string kMessageErrorPassword ("[HSMP] password_wrong");
Nunca se dice "wrong password" porque ahora el atacante sabe que el usuario existe y solo le queda hacer un ataque con ese nombre de usuario. Simplemente responder "wrong credentials".

2021-05-03 14:50 UTC, mgonnav commented on src/HSMP/HSMPResponse.cpp
> +  first_char = buffer[0];
Me parece que no es necesaria la variable `first_char`, además de que se ve mal tener que pasarla como parámetro. Si ProcessResponse devuelve `nullptr`, ya sabemos que se cerró la conexión. O en todo caso, añadir el `case '\0\: return nulltpr;` para ser más explícitos.

2021-05-03 14:50 UTC, mgonnav commented on src/server.cpp
> +    if ((req->type() == HSMP::kExitRequest) || (bytes_received <= 0)) {
No hay punto en usar una variable `bytes_received` ni hacer `bytes_received <= 0` porque si ProcessRequest detecta que el primer caracter es `'\0'`; es decir, que el socket ha sido cerrado por parte del cliente, devuelve un ExitRequest.
https://github.com/BasicAlgorithm/Protocol-HSM/blob/147a6751cd895c0115b1150e491d33f59d57c6f1/src/HSMP/HSMPRequest.cpp#L197-L198

2021-05-04 08:12 UTC, BasicAlgorithm commented
Most of suggestion implemented. @mgonnav  @rodp63

2021-05-04 13:43 UTC, rodp63 approved these changes
Seems good

2021-05-04 16:39 UTC, merged